### ISSUE TITLE
store arrays in flash

### ISSUE THREAD

**Issue by nerdralph** [jasonacox/TM1637TinyDisplay#3]
If you store the segment arrays like digitToSegment in PROGMEM it reduces the RAM usage.

**Comment by jasonacox** [comment]
Good suggestion!  It would save 111 bytes or so, which is helpful for small MCUs like the ATtiny.  It was a simple update and I just checked it in.  I want to verify it against a few more architectures and then I will release it as v1.3.0.

**Comment by jasonacox** [comment]
v1.3.0 released - thank you!
